.TH _printf 3  "23.07.24" "Version 1.0" "library function manual"
.SH NAME
_printf \- format and print data
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.B #include <stdarg.h>
.B #include "main.h"
.sp
.BI int _printf(const char *format, ...);
.fi
.SH DESCRIPTION
.B _printf
produces output according to a format as described below.
The function writes output to standard output, the format is a character string that may contain
format specifiers marked by the character '%', which specify how subsequent arguments
(or arguments accessed through the variable-length argument facilities of stdarg.h )
are converted for output.

The format specifiers supported are:
.sp
.TP
.B %c
Print a single character.
.TP
.B %s
Print a string of characters.
.TP
.B %d, %i
Print a signed decimal integer.
.TP
.B %%
Prints a literal '%' character.
.TP
.B %f
Prints a floating number.

.SH RETURN VALUE
The
.B _printf
function returns the number of characters printed (excluding the null byte used to end output to strings).
If an output error is encountered, a negative value is returned.
.sp
.SH EXEMPLES
.nf
#include <stdio.h>
#include "main.h"

int main(void)
{
	_printf("character: %c\n", 'A');
	_printf("string: %%s\n", "Hello, world");
	_printf("integer: %d\n", 12345);
	_printf("Percent sign: %%\n");
	_printf("Floating: %f\n", 3.93);
	return (0);
}
.fi
.SH SEE ALSO
.BR printf (3),
.BR putchar (3)
.SH AUTHOR
Written by Jean-paul & Guney